name: npm deploy
on:
  workflow_dispatch:

jobs:
  call-npm-package-checks:
    uses: OGS-GmbH/reusable-github-actions/.github/workflows/npm-package-checks.yml@main

  call-npm-package-publish:
    needs: call-npm-package-checks
    uses: OGS-GmbH/reusable-github-actions/.github/workflows/npm-package-publish.yml@main
    secrets:
      NPM_ORG_OGS_GMBH_CI: ${{ secrets.NPM_ORG_OGS_GMBH_CI }}
